# for module compiling
import os
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)

path = [cwd]
group = DefineGroup('Basesw', src = [' '], depend = [''], CPPPATH = path)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
